### ISSUE TITLE
Schlechter als Minicrust

### ISSUE THREAD

**Issue by L3P3** [Spickelbing/tcp-server#1]
Netter Versuch, mich in Rust einzuholen, aber dieses Projekt hat kein Protobuf drin, also kann das gar nicht so gut werden wie mein Minicrust.

Außerdem ist unklar, was das Ziel des Projektes ist und welche Funktionen es haben soll. Die Readme ist zu knapp.

**Comment by Spickelbing** [comment]
troll issue

**Comment by haitemura** [comment]
troll issue

**Comment by L3P3** [comment]
Die Readme ist trotzdem zu knapp. Verstehe nicht, was das Programm können soll und was nicht.

**Comment by haitemura** [comment]
Hab sie leicht angepasst, ich schreib mehr in die README sobald ich das hier einigermaßen benutzbar habe
